apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: ingress-nginx
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - testing.com
  rules:
    - host: jenkins.testing.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins-service-bridge
                port: 
                  number: 8080
    - host: dashboard.testing.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard-service-bridge
                port: 
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service-bridge
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: jenkins.devops-tools
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard-service-bridge
  namespace: ingress-nginx
spec:
  type: ExternalName
  externalName: kubernetes-dashboard.kubernetes-dashboard
