apiVersion: v1
kind: Pod
metadata:
  name: agents-pods
  namespace: devops-tools
spec:
  containers:
  - name: jnlp
    image: 'jenkins/inbound-agent'
    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']